name: ${name}
version: ${version}
website: ${project.url}
author: ${author}

main: ${project.groupId}.${project.artifactId}.Nifty${project.name}
softdepend: [Vault, ProtocolLib]

commands:
  nifty:
    description: Show status of plugins using ${name}
    usage: /<command> [page|plugin]

permissions:
  niftylibrary.*:
    description: Gives access to all plugin commands
    children:
      niftylibrary.nifty:
        description: Show status of plugins using ${name}