name: ${project.name}
version: ${project.version}
website: ${project.url}
author: ${author}

main: ${project.groupId}.${project.artifactId}.Nifty${project.name}
softdepend: [Vault, ProtocolLib]

commands:
  nifty:
    description: Show status of plugins using NiftyBukkit
    usage: /<command> [page|plugin]

permissions:
  niftybukkit.*:
    description: Gives access to all plugin commands
    children:
      niftybukkit.nifty:
        description: Show status of plugins using NiftyBukkit