name: NiftyBukkit
version: 3.3.7
website: https://netcoding.net/
author: Brian Graham (CraftedFury)

main: net.netcoding.niftybukkit.NiftyBukkit
softdepend: [Vault, ProtocolLib]

commands:
  nifty:
    description: Show status of plugins using NiftyBukkit
    usage: /<command> [page|plugin]

permissions:
  niftybukkit.*:
    description: Gives access to all plugin commands
    children:
      niftybukkit.nifty:
        description: Show status of plugins using NiftyBukkit